idclientb1	Cleartext-Password := "pwclientb1"
			Service-Type = Framed-User,
			Tunnel-Type = 13,
			Tunnel-Medium-Type = 6,
			Tunnel-Private-Group-ID = 32
		
idclientb2	Cleartext-Password := "pwclientb2"
			Service-Type = Framed-User,
			Tunnel-Type = 13,
			Tunnel-Medium-Type = 6,
			Tunnel-Private-Group-ID = 95