frr defaults traditional
hostname R101
service integrated-vtysh-config
!

! Loopback per router-id
interface lo
 ip address 2.255.0.101
 ip ospf area 0
!

! Link R101 <-> R102
interface eth0
 ip address 10.0.11.1/30
 ip ospf area 0
!

! Link R101 <-> R103
interface eth1
 ip address 10.0.11.5/30
 ip ospf area 0
!

! Link R101 <-> CE1
interface eth2
 ip address 10.1.1.1/30
 ip ospf area 0
!

router ospf
 ospf router-id 2.255.0.101
 passive-interface lo
!

router bgp 100
 bgp router-id 2.255.0.101

 ! iBGP verso R102 (loopback)
 neighbor 2.255.0.102 remote-as 100
 neighbor 2.255.0.102 update-source 2.255.0.101

 ! iBGP verso R103 (loopback)
 neighbor 2.255.0.103 remote-as 100
 neighbor 2.255.0.103 update-source 2.255.0.101

 address-family ipv4 unicast
  neighbor 2.255.0.102 next-hop-self
  neighbor 2.255.0.103 next-hop-self
 exit-address-family
!

line vty
!