client
dev tun
proto udp

# CE3 lato backbone: IP 10.0.3.2 (eth0 CE3, verso R103)
remote 10.0.3.2 1194

ca   /root/openvpn/keys/ca.crt
cert /root/openvpn/keys/CE1.crt
key  /root/openvpn/keys/CE1.key

# rete locale dietro CE1 (Site 1)
route 192.168.1.0 255.255.255.0

persist-key
persist-tun

verb 3