frr defaults traditional
hostname R102
service integrated-vtysh-config
!

! Loopback per router-id
interface lo
 ip address 2.255.0.102
 ip ospf area 0
!

! Link R102 <-> R101
interface eth0
 ip address 10.0.11.6/30
 ip ospf area 0
!

! Link R102 <-> R103
interface eth1
 ip address 10.0.11.9/30
 ip ospf area 0
!

! Link R102 <-> CE3
interface eth2
 ip address 10.1.3.1/30
 ip ospf area 0
!

router ospf
 ospf router-id 2.255.0.102
 passive-interface lo
!

router bgp 100
 bgp router-id 2.255.0.102

 ! iBGP verso R101 (loopback)
 neighbor 2.255.0.101 remote-as 100
 neighbor 2.255.0.101 update-source 2.255.0.102

 ! iBGP verso R103 (loopback)
 neighbor 2.255.0.103 remote-as 100
 neighbor 2.255.0.103 update-source 2.255.0.102

 address-family ipv4 unicast
  neighbor 2.255.0.101 next-hop-self
  neighbor 2.255.0.103 next-hop-self
 exit-address-family
!

line vty
!