frr defaults traditional
hostname R103
service integrated-vtysh-config
!

! Loopback per router-id
interface lo
 ip address 2.255.0.103/32
!

! Link R103 <-> R101
interface eth0
 ip address 10.0.11.2/30
!

! Link R103 <-> R102
interface eth1
 ip address 10.0.11.10/30
!

! Link R103 <-> CE2 (spoke VPN)
interface eth2
 ip address 10.1.2.1/30
!

router ospf
 ospf router-id 2.255.0.103
 network 2.255.0.103/32 area 0
 network 10.0.11.0/30 area 0
 network 10.0.11.8/30 area 0
 network 10.1.2.0/30 area 0
!

router bgp 100
 bgp router-id 2.255.0.103

 ! iBGP verso R101 (loopback)
 neighbor 2.255.0.101 remote-as 100
 neighbor 2.255.0.101 update-source 2.255.0.103

 ! iBGP verso R102 (loopback)
 neighbor 2.255.0.102 remote-as 100
 neighbor 2.255.0.102 update-source 2.255.0.103

 address-family ipv4 unicast
  neighbor 2.255.0.101 next-hop-self
  neighbor 2.255.0.102 next-hop-self
 exit-address-family
!

line vty
!