# /etc/hostapd/hostapd.conf
# Authenticator IEEE 802.1X cablato sul bridge br0

# Interfaccia e driver
interface=br0
driver=wired

# 802.1X / EAPOL
ieee8021x=1
use_pae_group_addr=1

# Identità del NAS inviata nelle richieste RADIUS
own_ip_addr=192.168.2.2
nas_identifier=ebpf-1

# Server RADIUS di autenticazione
auth_server_addr=192.168.3.2
auth_server_port=1812
auth_server_shared_secret=donttellit

# Logging su terminale/stdout
logger_stdout=-1
logger_stdout_level=2

# Interfaccia di controllo locale
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0