client
dev tun
proto udp

# stesso server CE3
remote 10.0.3.2 1194

ca   /root/openvpn/keys/ca.crt
cert /root/openvpn/keys/CE2.crt
key  /root/openvpn/keys/CE2.key

# reti locali dietro CE2 (VLAN 32 e 95)
route 192.168.32.0 255.255.255.0
route 192.168.95.0 255.255.255.0

persist-key
persist-tun

verb 3